name: Build AW Mac App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build macOS DMG
        run: npm run dist

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: AW-App-Mac-Installer
          path: dist/*.dmg